Sub Main ()

Dim currentDoc As AssemblyDocument = ThisApplication.ActiveDocument
AssemblyOriginCons(currentDoc)
	
End Sub


Sub AssemblyOriginCons(assemDef As AssemblyDocument)
	
'Sub that runs through the occurrences of the assembly to constraint their origin planes to those of the current aassembly 
'given that those occurrences have no prior existing constraints or that they are not part of pattern.

'Set planes assembly origin planes
Dim PlanoE1 As WorkPlane = assemDef.ComponentDefinition.WorkPlanes.Item(1)
Dim PlanoE2 As WorkPlane = assemDef.ComponentDefinition.WorkPlanes.Item(2)
Dim PlanoE3 As WorkPlane = assemDef.ComponentDefinition.WorkPlanes.Item(3)
	
For Each compOcc As ComponentOccurrence In assemDef.ComponentDefinition.Occurrences
	If compOcc.Constraints.Count = 0 And compOcc.PatternElement Is Nothing Then
	
	' Set occurrences ogigin planes
	    Dim Plano1 As WorkPlane = compOcc.Definition.Workplanes.Item(1) 
	    Dim Plano2 As WorkPlane = compOcc.Definition.Workplanes.Item(2) 
	    Dim Plano3 As WorkPlane = compOcc.Definition.Workplanes.Item(3) 
		
	' Set proxies for making the constraints
	    Dim APlano1 As WorkPlaneProxy
        compOcc.CreateGeometryProxy(Plano1,APlano1)
	    Dim APlano2 As WorkPlaneProxy
        compOcc.CreateGeometryProxy(Plano2,APlano2)
	    Dim APlano3 As WorkPlaneProxy
        compOcc.CreateGeometryProxy(Plano3, APlano3)
		
	' Constraints application
	    assemDef.ComponentDefinition.Constraints.AddFlushConstraint(APlano1,PlanoE1,0)
	    assemDef.ComponentDefinition.Constraints.AddFlushConstraint(APlano2,PlanoE2,0)
	    assemDef.ComponentDefinition.Constraints.AddFlushConstraint(APlano3,PlanoE3,0)
	
    End If
		
Next

End Sub	